import type { Metadata } from 'next';
import { Roboto, Geist } from 'next/font/google';
import './globals.css';
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-geist-sans',
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang='en' className={cn("h-full", "antialiased", roboto.variable, "font-sans", geist.variable)}>
      <body className='bg-amber-950' suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
