import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Header } from '@/components/shared';
import { Toaster } from '@/components/ui/sonner';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang='en'
      className={cn('w-[95%] m-auto', 'antialiased', 'font-sans', geist.variable)}
    >
      <body className='bg-[#eef7f1]' suppressHydrationWarning>
        <Header />
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
