import { ProductItem } from '@/types/product-item.type';

export const products: ProductItem[] = [
	{
		id: 1,
		title: 'Omega-3 950 MG Triple Strength',
		description:
			'It is a powerful immune booster and helps improve the elasticity of connective tissues.',
		image: '/products/omega-3.png',
		price: 499.99,
		brand: 'Solgar',
		rating: 5,
		category: 'recovery',
	},
	{
		id: 2,
		title: 'Biotin 5000 mcg',
		description: 'Supports healthy hair, skin, and nails while boosting energy metabolism.',
		image: '/products/biotin.png',
		price: 299.99,
		brand: 'Now Foods',
		rating: 1,
		category: 'recovery',
	},
	{
		id: 3,
		title: 'Magnesium + B6',
		description: 'Helps reduce stress, supports muscle function, and improves sleep quality.',
		image: '/products/magnesium-b6.png',
		price: 399.99,
		brand: 'Solgar',
		rating: 4.6,
		category: 'relax',
	},
	{
		id: 4,
		title: 'Skin, Nails & Hair',
		description: 'Advanced formula for strengthening hair, improving skin glow, and nail health.',
		image: '/products/skin-nails-hair.png',
		price: 459.99,
		brand: 'Solgar',
		rating: 1.5,
		category: 'relax',
	},
	{
		id: 5,
		title: 'Vitamin A 10000 IU',
		description: 'Supports vision, immune system, and healthy skin regeneration.',
		image: '/products/vitamin-A.png',
		price: 249.99,
		brand: 'Now Foods',
		rating: 4.3,
		category: 'sleep',
	},
	{
		id: 6,
		title: 'Vitamin C 1000 mg',
		description: 'Boosts immunity and helps fight oxidative stress in the body.',
		image: '/products/vitamin-C.png',
		price: 279.99,
		brand: 'Solgar',
		rating: 4.5,
		category: 'sleep',
	},
	{
		id: 7,
		title: 'Vitamin D3 2000 IU',
		description: 'Supports bone health, immune system, and mood balance.',
		image: '/products/vitamin-D3.png',
		price: 319.99,
		brand: 'Now Foods',
		rating: 3.5,
		category: 'focus',
	},
	{
		id: 8,
		title: 'Vitamin K2',
		description: 'Promotes proper calcium absorption and cardiovascular health.',
		image: '/products/vitamin-K2.png',
		price: 349.99,
		brand: 'Now Foods',
		rating: 2.4,
		category: 'focus',
	}
];